name: Push to Velog
on: [push] # 깃허브에 Push가 발생하면 실행!
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: velog-helper
        uses: sst606/velog-helper@main # 자동 연동 도구 사용
        with:
          token: ${{ secrets.VELOG_TOKEN }} # 금고에서 토큰을 꺼내서 인증